In [107]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [108]:
# Answer Here
a = np.arange(24).reshape(2, 3, 4)
np.sum(a)

276

# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [109]:
# Answer Here
b = np.random.randint(10,size=(2,3,4,5))
b

array([[[[4, 7, 5, 0, 0],
         [6, 1, 0, 4, 8],
         [7, 3, 4, 1, 3],
         [2, 6, 9, 9, 0]],

        [[8, 8, 4, 4, 4],
         [2, 1, 5, 5, 5],
         [0, 3, 0, 7, 7],
         [9, 4, 7, 5, 4]],

        [[3, 9, 8, 0, 3],
         [6, 7, 2, 4, 4],
         [5, 1, 4, 9, 4],
         [2, 2, 5, 5, 1]]],


       [[[9, 8, 6, 5, 4],
         [4, 7, 1, 3, 6],
         [4, 3, 0, 8, 0],
         [0, 3, 5, 8, 5]],

        [[5, 4, 7, 2, 4],
         [9, 7, 6, 9, 3],
         [6, 8, 3, 1, 9],
         [1, 0, 1, 8, 5]],

        [[5, 6, 8, 1, 3],
         [1, 6, 4, 8, 4],
         [5, 0, 7, 0, 6],
         [1, 9, 5, 9, 6]]]])

# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [110]:
# Answer Here
np.mean(b,axis=1)

array([[[5.        , 8.        , 5.66666667, 1.33333333, 2.33333333],
        [4.66666667, 3.        , 2.33333333, 4.33333333, 5.66666667],
        [4.        , 2.33333333, 2.66666667, 5.66666667, 4.66666667],
        [4.33333333, 4.        , 7.        , 6.33333333, 1.66666667]],

       [[6.33333333, 6.        , 7.        , 2.66666667, 3.66666667],
        [4.66666667, 6.66666667, 3.66666667, 6.66666667, 4.33333333],
        [5.        , 3.66666667, 3.33333333, 3.        , 5.        ],
        [0.66666667, 4.        , 3.66666667, 8.33333333, 5.33333333]]])

# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [111]:
# Answer Here
temp = np.random.randint(30,50,size=(7,24,60))
x = np.mean(temp,axis=(1,2))

Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [112]:
# Answer Here
temp2 = np.random.randint(30,50,size=(4,7,24,60))
np.max(temp2,axis=(1,2,3))

array([49, 49, 49, 49])

# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Input:

In [113]:
# Answer Here
x=np.random.randint(0,10,size=(100,50,3))
dimensions=np.mean(x,axis=(0,1))
print("length = ",dimensions[0])
print("width = ",dimensions[1])
print("height = ",dimensions[2])

length =  4.5686
width =  4.5732
height =  4.4584


# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [114]:
# Answer Here
y = np.random.randint(30,50,size=(5,6,7))
print("Total Measurements:",np.size(y))
print("Avg Measurement:",np.mean(y))
print("Standrad Deviation:",np.std(y))
print("Min Measurement:",np.min(y))
print("Max Measurement:",np.max(y))

Total Measurements: 210
Avg Measurement: 39.4
Standrad Deviation: 5.696448350465737
Min Measurement: 30
Max Measurement: 49


## randn()
### The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution. 

## randint()
### Return random integers 