# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [2]:
import numpy as np

In [70]:
# RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE
a = np.ones((3, 5)) 
print("a.shape=",a.shape)
b = np.ones((5,)).reshape(1, 5)
print("b.shape=",b.shape)
print(b[np.newaxis, :])

a.shape= (3, 5)
b.shape= (1, 5)
[[[1. 1. 1. 1. 1.]]]


In [67]:
# RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING
c=a+b
print(a.shape,b.shape)
print(c)

(3, 5) (1, 5)
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [71]:
# 1. Use reduce()
a = np.array([1,3,5,7,9])
print("1. reduce() = ",np.add.reduce(a))

#2. Use accumulate()
print("2. accumulate() = ",np.add.accumulate(a))

1. reduce() =  25
2. accumulate() =  [ 1  4  9 16 25]


### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [72]:
# Answer here
one = np.arange(10,80,5)
one

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [73]:
two = np.arange(5,47,3)
two

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [77]:
full = np.vstack((one,two))
full

array([[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75],
       [ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44]])

### Now use indexing to select the 5th 7th and 11th columns

In [82]:
# Answer here
full[:,[4,6,10]]

array([[30, 40, 60],
       [17, 23, 35]])

### Select the 2nd row and fourth-last to second-last columns

In [83]:
#Answer here
full[[1],-4:-1]

array([[35, 38, 41]])

### Select 3rd to 3rd last columns skipping every second column

In [84]:
# Answer here
full[:,2:-2]

array([[20, 25, 30, 35, 40, 45, 50, 55, 60, 65],
       [11, 14, 17, 20, 23, 26, 29, 32, 35, 38]])

###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [88]:
# Answer here
full[:,-3:2:-2]

array([[65, 55, 45, 35, 25],
       [38, 32, 26, 20, 14]])

### We will work with the following array:

In [90]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Use slicing only to select 3rd and last row along with 2nd and last columns

In [91]:
# Answer here
a[2:5:2,1:6:3]

array([[11, 14],
       [21, 24]])

### Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [92]:
# Answer here
a[::2,2:4]

array([[ 2,  3],
       [12, 13],
       [22, 23]])

### Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [93]:
# Answer here
a[[1,3,4],1:-1:2]

array([[ 6,  8],
       [16, 18],
       [21, 23]])

### Change the values 1, 10, 19 and 22 in the array to -2

In [94]:
# Answer
mask=[1,10,19,22]
indices=[0,2,3,4],[1,0,4,2]
b=a[indices]
a[indices]=-2
a

array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

### Repeat above using boolean indexing

In [95]:
# Answer here
a = np.arange(25).reshape(5, 5)
mask=np.array([[0,1,0,0,0],[0,0,0,0,0],[1,0,0,0,0],[0,0,0,0,1],[0,0,1,0,0]],dtype=bool)
b=a[mask]
a[mask]=-2
a

array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

### Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [96]:
# Answer here
a = np.arange(25).reshape(5, 5)
rows = a[[0,2,3],0:4:3]
rows

array([[ 0,  3],
       [10, 13],
       [15, 18]])

### Calculating the sum, min and max of all diagonal values

In [97]:
# Answer here
print(a)
print("Sum = ",np.sum(np.diagonal(a)))
print("Min = ",np.min(np.diagonal(a)))
print("Max = ",np.max(np.diagonal(a)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Sum =  60
Min =  0
Max =  24


### Calculate the sum of differences between the 2nd row and 2nd last column

In [98]:
# Answer here
sum = a[1]-a[:,-2]
print("2nd row - 2nd last column: ",sum)
total=np.sum(sum)
print("total: ",total)

2nd row - 2nd last column:  [  2  -2  -6 -10 -14]
total:  -30


### Create a new array that is the sum of even rows and odd rows

In [99]:
# Answer here
evenIndices=[2,4]
oddIndices=[1,3]
sum = a[evenIndices]+a[oddIndices]
sum

array([[15, 17, 19, 21, 23],
       [35, 37, 39, 41, 43]])

## You are done. Good job!